const MAX_REDIRECTS = 3;
const MEDIA_CACHE_SECONDS = 3600;

export default {
  async fetch(request, env) {
    const incomingUrl = new URL(request.url);
    const origin = normalizeOrigin(env.ORIGIN);
    if (!origin) {
      return new Response("ORIGIN is not configured", { status: 500 });
    }

    if (isOffloadPath(incomingUrl.pathname)) {
      return proxyOffload(request, incomingUrl, origin);
    }
    return proxyApplication(request, incomingUrl, origin);
  },
};

async function proxyApplication(request, incomingUrl, origin) {
  const target = new URL(incomingUrl.pathname + incomingUrl.search, origin);
  const upstreamRequest = new Request(target, request);
  upstreamRequest.headers.set("X-Forwarded-Proto", "https");
  const upstream = await fetch(upstreamRequest, { redirect: "manual" });

  if (upstream.status >= 300 && upstream.status < 400) {
    const headers = new Headers(upstream.headers);
    rewriteLocationHeader(headers, origin, incomingUrl.origin);
    return new Response(upstream.body, { status: upstream.status, headers });
  }

  const contentType = (upstream.headers.get("content-type") || "").toLowerCase();
  if (!contentType.includes("text/html")) {
    return upstream;
  }

  const body = (await upstream.text()).split(origin).join(incomingUrl.origin);
  const headers = new Headers(upstream.headers);
  headers.delete("content-length");
  headers.delete("content-encoding");
  headers.set("X-InstaFix-Edge", "cloudflare-worker-example");
  return new Response(body, { status: upstream.status, headers });
}

async function proxyOffload(request, incomingUrl, origin) {
  const originUrl = new URL(incomingUrl.pathname + incomingUrl.search, origin);
  const headers = new Headers(request.headers);
  headers.delete("range");
  headers.set("X-Forwarded-Proto", "https");

  let response;
  try {
    response = await fetch(originUrl, {
      method: request.method === "HEAD" ? "GET" : request.method,
      headers,
      redirect: "manual",
      cf: { cacheEverything: true, cacheTtl: 60 },
    });
  } catch {
    return new Response("offload origin unavailable", { status: 502 });
  }

  // compact=av4 is generated by InstaFix itself. Cache the completed MP4 at
  // the edge instead of asking the origin to regenerate/serve it repeatedly.
  if (response.status >= 200 && response.status < 300) {
    return edgeMediaResponse(response, request.method === "HEAD", "origin-compact");
  }

  if (response.status < 300 || response.status >= 400) {
    return response;
  }

  const location = response.headers.get("location");
  if (!location) return response;

  let target;
  try {
    target = new URL(location);
  } catch {
    return new Response("invalid media redirect", { status: 502 });
  }
  if (!isTrustedInstagramMedia(target)) {
    return new Response("untrusted media redirect", { status: 502 });
  }

  // External preview bots can follow Instagram's CDN redirect directly. This
  // keeps normal media bytes out of both the Worker and the InstaFix origin.
  if ((request.headers.get("sec-fetch-site") || "").toLowerCase() !== "same-origin") {
    return response;
  }

  const media = await fetchTrustedMedia(target, request.headers.get("accept") || "");
  if (!media) return response;
  return edgeMediaResponse(media, request.method === "HEAD", "instagram-cdn");
}

async function fetchTrustedMedia(initialUrl, accept) {
  let current = initialUrl;
  for (let hop = 0; hop <= MAX_REDIRECTS; hop++) {
    const headers = new Headers();
    if (accept) headers.set("accept", accept);

    let response;
    try {
      response = await fetch(current, {
        headers,
        redirect: "manual",
        cf: { cacheEverything: true, cacheTtl: MEDIA_CACHE_SECONDS },
      });
    } catch {
      return null;
    }

    if (response.status >= 300 && response.status < 400) {
      const location = response.headers.get("location");
      await response.body?.cancel();
      if (!location || hop === MAX_REDIRECTS) return null;
      try {
        current = new URL(location, current);
      } catch {
        return null;
      }
      if (!isTrustedInstagramMedia(current)) return null;
      continue;
    }

    if (!response.ok) return null;
    return isTrustedInstagramMedia(new URL(response.url || current.href)) ? response : null;
  }
  return null;
}

function edgeMediaResponse(media, headOnly, source) {
  const headers = new Headers();
  headers.set("content-type", media.headers.get("content-type") || "application/octet-stream");
  headers.set("cache-control", `public, max-age=${MEDIA_CACHE_SECONDS}`);
  headers.set("cross-origin-resource-policy", "cross-origin");
  headers.set("X-InstaFix-Edge", "cloudflare-worker-example");
  headers.set("X-InstaFix-Edge-Media", source);
  return new Response(headOnly ? null : media.body, { status: 200, headers });
}

function isOffloadPath(pathname) {
  return /^\/offload\/[A-Za-z0-9_-]{3,128}\/\d{1,2}(?:\.mp4)?$/.test(pathname);
}

function isTrustedInstagramMedia(url) {
  if (url.protocol !== "https:" || url.username || url.password || url.port) return false;
  const host = url.hostname.toLowerCase().replace(/\.$/, "");
  return host === "cdninstagram.com" || host.endsWith(".cdninstagram.com") ||
    host === "fbcdn.net" || host.endsWith(".fbcdn.net");
}

function normalizeOrigin(raw) {
  try {
    const url = new URL(raw || "");
    if (url.protocol !== "https:" || url.username || url.password || url.pathname !== "/") return "";
    return url.origin;
  } catch {
    return "";
  }
}

function rewriteLocationHeader(headers, origin, publicOrigin) {
  const location = headers.get("location");
  if (location && location.startsWith(origin)) {
    headers.set("location", publicOrigin + location.slice(origin.length));
  }
}
